/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railwaypro;

import java.awt.HeadlessException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author pc
 */
public class tkBk extends javax.swing.JFrame {

    /**
     * Creates new form tkBk
     */
    public tkBk() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDateEditor1 = new com.toedter.calendar.JTextFieldDateEditor();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        seat = new javax.swing.JComboBox<>();
        coach = new javax.swing.JComboBox<>();
        age = new javax.swing.JComboBox<>();
        book = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        no = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cnic = new javax.swing.JTextField();
        clas1 = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        frmSt = new javax.swing.JComboBox<>();
        toSt = new javax.swing.JComboBox<>();
        train = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        direction = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JDateChooser();
        book1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fare = new javax.swing.JLabel();
        sh = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jTextFieldDateEditor1.setText("jTextFieldDateEditor1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        seat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seat", "Birth" }));
        seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatActionPerformed(evt);
            }
        });

        coach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coach 1", "Coach 2", "Coach 3" }));
        coach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachActionPerformed(evt);
            }
        });

        age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHILD (3-9 years)", "ADULT (10-65 years)", "ELDERLY (above 65)", "DISABLED" }));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });

        book.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book.setText("Book");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATE");

        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMouseClicked(evt);
            }
        });
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NAME");

        name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONTACT");

        contact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CNIC");

        cnic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cnic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicActionPerformed(evt);
            }
        });

        clas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "AC Standard", "Bussiness Class" }));
        clas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clas1ActionPerformed(evt);
            }
        });

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        frmSt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmStActionPerformed(evt);
            }
        });

        toSt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toStActionPerformed(evt);
            }
        });

        train.setBorder(null);
        train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Search Train");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        direction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Up", "Down" }));
        direction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directionActionPerformed(evt);
            }
        });

        book1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book1.setText("Check Availability");
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CLASS");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SEAT/BIRTH/NO.");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FROM STATION");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TO STATION");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DIRECTION");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("AGE");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("COACH NO.");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("GENDER");

        fare.setBackground(new java.awt.Color(255, 255, 255));
        fare.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fare.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        sh.setBackground(new java.awt.Color(255, 255, 255));
        sh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("FARE");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Departure Time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(train, 0, 230, Short.MAX_VALUE))
                    .addComponent(book1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(frmSt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cnic, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clas1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(seat, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toSt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(direction, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(age, 0, 328, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(13, 13, 13))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clas1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(direction, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frmSt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toSt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(train, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fare, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railwaypro/railway.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        
    }//GEN-LAST:event_ageActionPerformed

    private void seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatActionPerformed
        if (seat.getSelectedItem().equals("Seat")){
            no.removeAllItems();
            no.addItem("61");
            no.addItem("62");
            no.addItem("63");
            no.addItem("64");
            no.addItem("65");
            no.addItem("66");
            no.addItem("67");
            no.addItem("68");
            no.addItem("69");
            no.addItem("70");
            no.addItem("71");
            no.addItem("72");
            no.addItem("73");
            no.addItem("74");
            no.addItem("75");
            no.addItem("76");
            no.addItem("77");
            no.addItem("78");
        }
        else if (seat.getSelectedItem().equals("Birth")){
            no.removeAllItems();
            no.addItem("1");
            no.addItem("2");
            no.addItem("3");
            no.addItem("4");
            no.addItem("5");
            no.addItem("6");
            no.addItem("7");
            no.addItem("8");
            no.addItem("9");
            no.addItem("10");
            no.addItem("11");
            no.addItem("12");
            no.addItem("13");
            no.addItem("14");
            no.addItem("15");
            no.addItem("16");
            no.addItem("17");
            no.addItem("18");
            no.addItem("19");
            no.addItem("20");
            no.addItem("21");
            no.addItem("22");
            no.addItem("23");
            no.addItem("24");
            no.addItem("25");
            no.addItem("26");
            no.addItem("27");
            no.addItem("28");
            no.addItem("29");
            no.addItem("30");
            no.addItem("31");
            no.addItem("32");
            no.addItem("33");
            no.addItem("34");
            no.addItem("35");
            no.addItem("36");
            no.addItem("37");
            no.addItem("38");
            no.addItem("39");
            no.addItem("40");
            no.addItem("41");
            no.addItem("42");
            no.addItem("43");
            no.addItem("44");
            no.addItem("45");
            no.addItem("46");
            no.addItem("47");
            no.addItem("48");
            no.addItem("49");
            no.addItem("50");
            no.addItem("51");
            no.addItem("52");
            no.addItem("53");
            no.addItem("54");
            no.addItem("55");
            no.addItem("56");
            no.addItem("57");
            no.addItem("58");
            no.addItem("59");
            no.addItem("60");
        }
    }//GEN-LAST:event_seatActionPerformed

    private void coachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
     RailwayPro rp = new RailwayPro();
     //String Name = name.getText();
        String date1 = ((JTextField)date.getDateEditor().getUiComponent()).getText();
            rp.booking((String)clas1.getSelectedItem(),(String)coach.getSelectedItem(),
             (String)seat.getSelectedItem(),(String)no.getSelectedItem(), 
             date1,name.getText(), contact.getText(), cnic.getText(),
             (String)gender.getSelectedItem(),(String)age.getSelectedItem(),
             (String)frmSt.getSelectedItem(),(String)toSt.getSelectedItem(),(String)train.getSelectedItem());
             JOptionPane.showMessageDialog(this, "Booked");
               dispose();
               ticket t = new ticket(name.getText(),cnic.getText(),
               fare.getText(),contact.getText(),(String)gender.getSelectedItem(),
               (String)frmSt.getSelectedItem(),(String)toSt.getSelectedItem(),
               (String)coach.getSelectedItem(),
               (String)seat.getSelectedItem(),(String)no.getSelectedItem(),
               (String)clas1.getSelectedItem(),sh.getText(),
               ((JTextField)date.getDateEditor().getUiComponent()).getText(),
               (String)train.getSelectedItem());
               t.setVisible(true);
               dispose();
          
    }//GEN-LAST:event_bookActionPerformed

    private void cnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicActionPerformed

    private void clas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clas1ActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void frmStActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmStActionPerformed
        if(direction.getSelectedItem().equals("Up")){
        if(frmSt.getSelectedItem().equals("Karachi")){
            toSt.removeAllItems();
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
            toSt.addItem("Sahiwal");
            toSt.addItem("Faisalabad");
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Hyderabad")){
            toSt.removeAllItems();
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
            toSt.addItem("Sahiwal");
            toSt.addItem("Faisalabad");
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Rohri")){
            toSt.removeAllItems();
            toSt.addItem("Khanewal");
            toSt.addItem("Sahiwal");
            toSt.addItem("Faisalabad");
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Khanewal")){     
            toSt.removeAllItems();
            toSt.addItem("Faisalabad");
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Sahiwal")){  
            toSt.removeAllItems();
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Faisalabad")){
            toSt.removeAllItems();
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Lahore")){
            toSt.removeAllItems();
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Sialkot")){
            toSt.removeAllItems();
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Gujrat")){
            toSt.removeAllItems();
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Jehlum")){
            toSt.removeAllItems();
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Islamabad")){
            toSt.removeAllItems();
            toSt.addItem("Rawalpindi");
            toSt.addItem("Peshawar");
        }else if(frmSt.getSelectedItem().equals("Rawalpindi")){
            toSt.removeAllItems();
            toSt.addItem("Peshawar");
        }
        }else if(direction.getSelectedItem().equals("Down")){
            if(frmSt.getSelectedItem().equals("Peshawar")){
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
            toSt.addItem("Sahiwal");
            toSt.addItem("Faisalabad");
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
            toSt.addItem("Rawalpindi");
        }else if(frmSt.getSelectedItem().equals("Rawalpindi")){
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
            toSt.addItem("Sahiwal");
            toSt.addItem("Faisalabad");
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
            toSt.addItem("Islamabad");
        }else if(frmSt.getSelectedItem().equals("Islamabad")){
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
            toSt.addItem("Sahiwal");
            toSt.addItem("Faisalabad");
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
            toSt.addItem("Jehlum");
        }else if(frmSt.getSelectedItem().equals("Jehlum")){
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
            toSt.addItem("Sahiwal");
            toSt.addItem("Faisalabad");
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
            toSt.addItem("Gujrat");
        }else if(frmSt.getSelectedItem().equals("Gujrat")){
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
            toSt.addItem("Sahiwal");
            toSt.addItem("Faisalabad");
            toSt.addItem("Lahore");
            toSt.addItem("Sialkot");
        }else if(frmSt.getSelectedItem().equals("Sialkot")){
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
            toSt.addItem("Sahiwal");
            toSt.addItem("Faisalabad");
            toSt.addItem("Lahore");
        }else if(frmSt.getSelectedItem().equals("Lahore")){
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
            toSt.addItem("Sahiwal");
            toSt.addItem("Faisalabad");
        }else if(frmSt.getSelectedItem().equals("Faisalabad")){
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
        }else if(frmSt.getSelectedItem().equals("Khanewal")){     
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
        }else if(frmSt.getSelectedItem().equals("Sahiwal")){     
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
            toSt.addItem("Rohri");
            toSt.addItem("Khanewal");
        }else if(frmSt.getSelectedItem().equals("Rohri")){     
            toSt.removeAllItems();
            toSt.addItem("Karachi");
            toSt.addItem("Hyderabad");
        }else if(frmSt.getSelectedItem().equals("Hyderabad")){     
            toSt.removeAllItems();
            toSt.addItem("Karachi");
        }
        }
    }//GEN-LAST:event_frmStActionPerformed

    private void toStActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toStActionPerformed

        
    }//GEN-LAST:event_toStActionPerformed

    private void trainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainActionPerformed

    }//GEN-LAST:event_trainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(direction.getSelectedItem().equals("Up")){
        if((frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Hyderabad") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Rohri") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Khanewal")) ||
           (frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Lahore")) ||      
          (frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Rohri") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Khanewal") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Khanewal"))){
           train.removeAllItems();
           train.addItem("Pakistan Express");
           train.addItem("Rehman Baba Express");
           train.addItem("Korakaram Express");
           train.addItem("Shalimar Express");
           train.addItem("Bussiness Express");
        }else if((frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Hyderabad") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Rohri") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Khanewal")) ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Faisalabad") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Lahore") ||
          (frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Rohri") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Khanewal") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Faisalabad") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Lahore") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Khanewal") || 
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Faisalabad") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Lahore") ||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Faisalabad") ||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Lahore")) ||
           frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Lahore") ){
           train.removeAllItems();
           train.addItem("Pakistan Express");
           train.addItem("Rehman Baba Express");
           train.addItem("Korakaram Express");
        }else if((frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Hyderabad") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Rohri") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Khanewal")) ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Sahiwal") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Lahore") ||
          (frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Rohri") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Khanewal") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Sahiwal") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Lahore") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Khanewal") || 
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Sahiwal") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Lahore") ||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Sahiwal") ||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Lahore")) ||
           frmSt.getSelectedItem().equals("Sahiwal") && toSt.getSelectedItem().equals("Lahore")){
           train.removeAllItems();
           train.addItem("Shalimar Express");
           train.addItem("Bussiness Express");
        }else if((frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Hyderabad") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Rohri") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Khanewal") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Faisalabad") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Lahore") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Sialkot") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Gujrat") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Jehlum") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Islamabad") ||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Rawalpindi")||
           frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Peshawar"))     || 
         (  frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Rohri") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Khanewal") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Faisalabad") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Lahore") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Sialkot") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Gujrat") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Jehlum") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Islamabad") ||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Rawalpindi")||
           frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Peshawar"))     || 
         ( frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Khanewal") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Faisalabad") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Lahore") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Sialkot") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Gujrat") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Jehlum") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Islamabad") ||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Rawalpindi")||
           frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Peshawar"))          ||
         ( frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Faisalabad") ||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Lahore") ||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Sialkot") ||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Gujrat") ||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Jehlum") ||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Islamabad") ||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Rawalpindi")||
           frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Peshawar"))       ||
         ( frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Lahore") ||
           frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Sialkot") ||
           frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Gujrat") ||
           frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Jehlum") ||
           frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Islamabad") ||
           frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Rawalpindi")||
           frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Peshawar"))  || 
         ( frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Sialkot") ||
           frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Gujrat") ||
           frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Jehlum") ||
           frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Islamabad") ||
           frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Rawalpindi")||
           frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Peshawar")) ||
         ( frmSt.getSelectedItem().equals("Sialkot") && toSt.getSelectedItem().equals("Gujrat") ||
           frmSt.getSelectedItem().equals("Sialkot") && toSt.getSelectedItem().equals("Jehlum") ||
           frmSt.getSelectedItem().equals("Sialkot") && toSt.getSelectedItem().equals("Islamabad") ||
           frmSt.getSelectedItem().equals("Sialkot") && toSt.getSelectedItem().equals("Rawalpindi")||
           frmSt.getSelectedItem().equals("Sialkot") && toSt.getSelectedItem().equals("Peshawar")) || 
         ( frmSt.getSelectedItem().equals("Gujrat") && toSt.getSelectedItem().equals("Jehlum") ||
           frmSt.getSelectedItem().equals("Gujrat") && toSt.getSelectedItem().equals("Islamabad") ||
           frmSt.getSelectedItem().equals("Gujrat") && toSt.getSelectedItem().equals("Rawalpindi")||
           frmSt.getSelectedItem().equals("Gujrat") && toSt.getSelectedItem().equals("Peshawar")) ||
         ( frmSt.getSelectedItem().equals("Jehlum") && toSt.getSelectedItem().equals("Islamabad") ||
           frmSt.getSelectedItem().equals("Jehlum") && toSt.getSelectedItem().equals("Rawalpindi")||
           frmSt.getSelectedItem().equals("Jehlum") && toSt.getSelectedItem().equals("Peshawar")) ||
         ( frmSt.getSelectedItem().equals("Islamabad") && toSt.getSelectedItem().equals("Rawalpindi")||
           frmSt.getSelectedItem().equals("Islamabad") && toSt.getSelectedItem().equals("Peshawar")) ||
         ( frmSt.getSelectedItem().equals("Rawalpindi") && toSt.getSelectedItem().equals("Peshawar"))){
            train.removeAllItems();
           train.addItem("Pakistan Express");
           train.addItem("Rehman Baba Express");
        }
        }
         if(direction.getSelectedItem().equals("Down")){
            if((toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Hyderabad") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Rohri") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Khanewal")) ||
           (toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Lahore")) ||      
          (toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Rohri") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Khanewal") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Khanewal"))){
           train.removeAllItems();
           train.addItem("Pakistan Express");
           train.addItem("Rehman Baba Express");
           train.addItem("Korakaram Express");
           train.addItem("Shalimar Express");
           train.addItem("Bussiness Express");
        }else if((toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Hyderabad") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Rohri") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Khanewal")) ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Faisalabad") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Lahore") ||
          (toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Rohri") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Khanewal") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Faisalabad") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Lahore") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Khanewal") || 
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Faisalabad") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Lahore") ||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Faisalabad") ||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Lahore")) ||
           toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Lahore") ){
           train.removeAllItems();
           train.addItem("Pakistan Express");
           train.addItem("Rehman Baba Express");
           train.addItem("Korakaram Express");
        }else if((toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Hyderabad") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Rohri") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Khanewal")) ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Sahiwal") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Lahore") ||
          (toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Rohri") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Khanewal") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Sahiwal") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Lahore") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Khanewal") || 
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Sahiwal") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Lahore") ||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Sahiwal") ||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Lahore")) ||
           toSt.getSelectedItem().equals("Sahiwal") && frmSt.getSelectedItem().equals("Lahore")){
           train.removeAllItems();
           train.addItem("Shalimar Express");
           train.addItem("Bussiness Express");
        }else if((toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Hyderabad") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Rohri") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Khanewal") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Faisalabad") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Lahore") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Sialkot") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Gujrat") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Jehlum") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Islamabad") ||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Rawalpindi")||
           toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Peshawar"))     || 
         (  toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Rohri") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Khanewal") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Faisalabad") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Lahore") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Sialkot") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Gujrat") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Jehlum") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Islamabad") ||
           toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Rawalpindi")||
           toSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Peshawar"))     || 
         ( toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Khanewal") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Faisalabad") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Lahore") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Sialkot") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Gujrat") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Jehlum") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Islamabad") ||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Rawalpindi")||
           toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Peshawar"))          ||
         ( toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Faisalabad") ||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Lahore") ||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Sialkot") ||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Gujrat") ||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Jehlum") ||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Islamabad") ||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Rawalpindi")||
           toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Peshawar"))       ||
         ( toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Lahore") ||
           toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Sialkot") ||
           toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Gujrat") ||
           toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Jehlum") ||
           toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Islamabad") ||
           toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Rawalpindi")||
           toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Peshawar"))  || 
         ( toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Sialkot") ||
           toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Gujrat") ||
           toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Jehlum") ||
           toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Islamabad") ||
           toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Rawalpindi")||
           toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Peshawar")) ||
         ( toSt.getSelectedItem().equals("Sialkot") && frmSt.getSelectedItem().equals("Gujrat") ||
           toSt.getSelectedItem().equals("Sialkot") && frmSt.getSelectedItem().equals("Jehlum") ||
           toSt.getSelectedItem().equals("Sialkot") && frmSt.getSelectedItem().equals("Islamabad") ||
           toSt.getSelectedItem().equals("Sialkot") && frmSt.getSelectedItem().equals("Rawalpindi")||
           toSt.getSelectedItem().equals("Sialkot") && frmSt.getSelectedItem().equals("Peshawar")) || 
         ( toSt.getSelectedItem().equals("Gujrat") && frmSt.getSelectedItem().equals("Jehlum") ||
           toSt.getSelectedItem().equals("Gujrat") && frmSt.getSelectedItem().equals("Islamabad") ||
           toSt.getSelectedItem().equals("Gujrat") && frmSt.getSelectedItem().equals("Rawalpindi")||
           toSt.getSelectedItem().equals("Gujrat") && frmSt.getSelectedItem().equals("Peshawar")) ||
         ( toSt.getSelectedItem().equals("Jehlum") && frmSt.getSelectedItem().equals("Islamabad") ||
           toSt.getSelectedItem().equals("Jehlum") && frmSt.getSelectedItem().equals("Rawalpindi")||
           toSt.getSelectedItem().equals("Jehlum") && frmSt.getSelectedItem().equals("Peshawar")) ||
         ( toSt.getSelectedItem().equals("Islamabad") && frmSt.getSelectedItem().equals("Rawalpindi")||
           toSt.getSelectedItem().equals("Islamabad") && frmSt.getSelectedItem().equals("Peshawar")) ||
         ( toSt.getSelectedItem().equals("Rawalpindi") && frmSt.getSelectedItem().equals("Peshawar"))){
            train.removeAllItems();
           train.addItem("Pakistan Express");
           train.addItem("Rehman Baba Express");
        }
        //    children
        }
         
         if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("CHILD (3-9 years)") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Seat") &&
                clas1.getSelectedItem().equals("Economy")
           )){
            fare.setText("250");
            sh.setText("1:30");
        }else if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("CHILD (3-9 years)") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Birth") &&
                clas1.getSelectedItem().equals("Economy")
           )){
            fare.setText("300");
            sh.setText("1:30");
        }else if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("CHILD (3-9 years)") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Birth") &&
                clas1.getSelectedItem().equals("AC Standard")
           )){
            fare.setText("500");
            sh.setText("1:30");
        }else if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("CHILD (3-9 years)") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Birth") &&
                clas1.getSelectedItem().equals("Bussiness Class")
           )){
            fare.setText("600");
            sh.setText("1:30");
        }
        
//          Adult
        
        else if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("ADULT (10-65 years)") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Seat") &&
                clas1.getSelectedItem().equals("Economy")
           )){
            fare.setText("550");
            sh.setText("1:30");
        }else if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("ADULT (10-65 years)") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Birth") &&
                clas1.getSelectedItem().equals("Economy")
           )){
            fare.setText("600");
            sh.setText("1:30");
        }else if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("ADULT (10-65 years))") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Birth") &&
                clas1.getSelectedItem().equals("AC Standard")
           )){
            fare.setText("1000");
            sh.setText("1:30");
        }else if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("ADULT (10-65 years)") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Birth") &&
                clas1.getSelectedItem().equals("Bussiness Class")
           )){
            fare.setText("1150");
            sh.setText("1:30");
        }
   //           disabled

 if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("DISABLED") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Seat") &&
                clas1.getSelectedItem().equals("Economy")
           )){
            fare.setText("250");
            sh.setText("1:30");
        }else if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("DISABLED") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Birth") &&
                clas1.getSelectedItem().equals("Economy")
           )){
            fare.setText("300");
            sh.setText("1:30");
        }else if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("DISABLED") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Birth") &&
                clas1.getSelectedItem().equals("AC Standard")
           )){
            fare.setText("500");
            sh.setText("1:30");
        }else if((frmSt.getSelectedItem().equals("Karachi" ) && toSt.getSelectedItem().equals("Hyderabad") 
           && age.getSelectedItem().equals("DISABLED") 
           && train.getSelectedItem().equals("Pakistan Express")
           && seat.getSelectedItem().equals("Birth") &&
                clas1.getSelectedItem().equals("Bussiness Class")
           )){
            fare.setText("600");
            sh.setText("1:30");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void directionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionActionPerformed
            if(direction.getSelectedItem().equals("Up")){
            frmSt.removeAllItems();
            //frmSt.addItem("Karachi");
            frmSt.addItem("Hyderabad");
            frmSt.addItem("Rohri");
            frmSt.addItem("Khanewal");
            frmSt.addItem("Sahiwal");
            frmSt.addItem("Faisalabad");
            frmSt.addItem("Lahore");
            frmSt.addItem("Sialkot");
            frmSt.addItem("Gujrat");
            frmSt.addItem("Jehlum");
            frmSt.addItem("Islamabad");
            frmSt.addItem("Rawalpindi");
            frmSt.addItem("Karachi");
            }
            if(direction.getSelectedItem().equals("Down")){
            frmSt.removeAllItems();
            frmSt.addItem("Hyderabad");
            frmSt.addItem("Rohri");
            frmSt.addItem("Khanewal");
            frmSt.addItem("Sahiwal");
            frmSt.addItem("Faisalabad");
            frmSt.addItem("Lahore");
            frmSt.addItem("Sialkot");
            frmSt.addItem("Gujrat");
            frmSt.addItem("Jehlum");
            frmSt.addItem("Islamabad");
            frmSt.addItem("Rawalpindi");
            frmSt.addItem("Peshawar");        }
    }//GEN-LAST:event_directionActionPerformed

    private void noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseClicked
        
    }//GEN-LAST:event_noMouseClicked

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        // TODO add your handling code here:
        ResultSet rs = null; 
    RailwayPro rp = new RailwayPro();
        try {
            rs=rp.ticketMatcher(((JTextField)date.getDateEditor().getUiComponent()).getText()
                    ,(String)seat.getSelectedItem(),(String)no.getSelectedItem(), (String)clas1.getSelectedItem()
                    ,(String) coach.getSelectedItem(), (String)frmSt.getSelectedItem(),
                    (String) toSt.getSelectedItem(),(String) train.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(tkBk.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        try{
//            if(rs.next()){
//                rs.getString("date");
//                rs.getString("seat");
//                rs.getString("seatNo");
//                rs.getString("class1");
//                rs.getString("coach");
//                rs.getString("From_Station");
//                rs.getString("To_Station");
//                rs.getString("Train");
//            }
//        }catch(HeadlessException | SQLException e){
//            JOptionPane.showMessageDialog(this,e);
//        }
        
    }//GEN-LAST:event_book1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tkBk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tkBk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tkBk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tkBk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tkBk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> age;
    private javax.swing.JButton book;
    private javax.swing.JButton book1;
    private javax.swing.JComboBox<String> clas1;
    private javax.swing.JTextField cnic;
    private javax.swing.JComboBox<String> coach;
    private javax.swing.JTextField contact;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JComboBox<String> direction;
    private javax.swing.JLabel fare;
    private javax.swing.JComboBox<String> frmSt;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.toedter.calendar.JTextFieldDateEditor jTextFieldDateEditor1;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> no;
    private javax.swing.JComboBox<String> seat;
    private javax.swing.JLabel sh;
    private javax.swing.JComboBox<String> toSt;
    private javax.swing.JComboBox<String> train;
    // End of variables declaration//GEN-END:variables
}
