/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railwaypro;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pc
 */
public class userinterface extends javax.swing.JFrame {

    /**
     * Creates new form userinterface
     */
    public userinterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooserBeanInfo1 = new com.toedter.calendar.JDayChooserBeanInfo();
        jDayChooserBeanInfo2 = new com.toedter.calendar.JDayChooserBeanInfo();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        frmSt = new javax.swing.JComboBox<>();
        toSt = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        train = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        coach = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railwaypro/railway.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        frmSt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "From Station", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        frmSt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frmSt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmStActionPerformed(evt);
            }
        });

        toSt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "To Station", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        toSt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toSt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toStActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Search Train");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        train.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Train", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        train.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Check");
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton2MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        coach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UP", "DOWN" }));
        coach.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direction", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        coach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        coach.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                coachItemStateChanged(evt);
            }
        });
        coach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coachMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coachMousePressed(evt);
            }
        });
        coach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachActionPerformed(evt);
            }
        });
        coach.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                coachPropertyChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Train Schedule");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frmSt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toSt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(train, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coach, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(frmSt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toSt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(train, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train Departure", "Train Arrival", "From Station", "To Station", "Fare Economy", "Fare AC Standard", "Fare Bussiness"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Book Ticket");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 102, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        //this.jButton2.setForeground(Color.GREEN);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved

        //this.jButton2.setForeground(Color.GREEN);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseDragged
        //this.jButton2.setForeground(Color.GREEN);
    }//GEN-LAST:event_jButton2MouseDragged

    private void trainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainActionPerformed
        
    }//GEN-LAST:event_trainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(coach.getSelectedItem().equals("UP")){
            if((frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Hyderabad") ||
                frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Rohri") ||
                frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Khanewal")) ||
            (frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Lahore")) ||
            (frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Rohri") ||
                frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Khanewal") ||
                frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Khanewal"))){
            train.removeAllItems();
            train.addItem("Pakistan Express");
            train.addItem("Rehman Baba Express");
            train.addItem("Korakaram Express");
            train.addItem("Shalimar Express");
            train.addItem("Bussiness Express");
        }else if((frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Hyderabad") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Rohri") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Khanewal")) ||
        frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Faisalabad") ||
        frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Lahore") ||
        (frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Rohri") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Khanewal") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Faisalabad") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Lahore") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Khanewal") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Faisalabad") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Lahore") ||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Faisalabad") ||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Lahore")) ||
        frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Lahore") ){
        train.removeAllItems();
        train.addItem("Pakistan Express");
        train.addItem("Rehman Baba Express");
        train.addItem("Korakaram Express");
        }else if((frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Hyderabad") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Rohri") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Khanewal")) ||
        frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Sahiwal") ||
        frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Lahore") ||
        (frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Rohri") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Khanewal") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Sahiwal") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Lahore") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Khanewal") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Sahiwal") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Lahore") ||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Sahiwal") ||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Lahore")) ||
        frmSt.getSelectedItem().equals("Sahiwal") && toSt.getSelectedItem().equals("Lahore")){
        train.removeAllItems();
        train.addItem("Shalimar Express");
        train.addItem("Bussiness Express");
        }else if((frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Hyderabad") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Rohri") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Khanewal") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Faisalabad") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Lahore") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Sialkot") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Gujrat") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Jehlum") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Islamabad") ||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Rawalpindi")||
            frmSt.getSelectedItem().equals("Karachi") && toSt.getSelectedItem().equals("Peshawar"))     ||
        (  frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Rohri") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Khanewal") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Faisalabad") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Lahore") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Sialkot") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Gujrat") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Jehlum") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Islamabad") ||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Rawalpindi")||
            frmSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Peshawar"))     ||
        ( frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Khanewal") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Faisalabad") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Lahore") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Sialkot") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Gujrat") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Jehlum") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Islamabad") ||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Rawalpindi")||
            frmSt.getSelectedItem().equals("Rohri") && toSt.getSelectedItem().equals("Peshawar"))          ||
        ( frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Faisalabad") ||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Lahore") ||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Sialkot") ||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Gujrat") ||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Jehlum") ||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Islamabad") ||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Rawalpindi")||
            frmSt.getSelectedItem().equals("Khanewal") && toSt.getSelectedItem().equals("Peshawar"))       ||
        ( frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Lahore") ||
            frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Sialkot") ||
            frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Gujrat") ||
            frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Jehlum") ||
            frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Islamabad") ||
            frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Rawalpindi")||
            frmSt.getSelectedItem().equals("Faisalabad") && toSt.getSelectedItem().equals("Peshawar"))  ||
        ( frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Sialkot") ||
            frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Gujrat") ||
            frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Jehlum") ||
            frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Islamabad") ||
            frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Rawalpindi")||
            frmSt.getSelectedItem().equals("Lahore") && toSt.getSelectedItem().equals("Peshawar")) ||
        ( frmSt.getSelectedItem().equals("Sialkot") && toSt.getSelectedItem().equals("Gujrat") ||
            frmSt.getSelectedItem().equals("Sialkot") && toSt.getSelectedItem().equals("Jehlum") ||
            frmSt.getSelectedItem().equals("Sialkot") && toSt.getSelectedItem().equals("Islamabad") ||
            frmSt.getSelectedItem().equals("Sialkot") && toSt.getSelectedItem().equals("Rawalpindi")||
            frmSt.getSelectedItem().equals("Sialkot") && toSt.getSelectedItem().equals("Peshawar")) ||
        ( frmSt.getSelectedItem().equals("Gujrat") && toSt.getSelectedItem().equals("Jehlum") ||
            frmSt.getSelectedItem().equals("Gujrat") && toSt.getSelectedItem().equals("Islamabad") ||
            frmSt.getSelectedItem().equals("Gujrat") && toSt.getSelectedItem().equals("Rawalpindi")||
            frmSt.getSelectedItem().equals("Gujrat") && toSt.getSelectedItem().equals("Peshawar")) ||
        ( frmSt.getSelectedItem().equals("Jehlum") && toSt.getSelectedItem().equals("Islamabad") ||
            frmSt.getSelectedItem().equals("Jehlum") && toSt.getSelectedItem().equals("Rawalpindi")||
            frmSt.getSelectedItem().equals("Jehlum") && toSt.getSelectedItem().equals("Peshawar")) ||
        ( frmSt.getSelectedItem().equals("Islamabad") && toSt.getSelectedItem().equals("Rawalpindi")||
            frmSt.getSelectedItem().equals("Islamabad") && toSt.getSelectedItem().equals("Peshawar")) ||
        ( frmSt.getSelectedItem().equals("Rawalpindi") && toSt.getSelectedItem().equals("Peshawar"))){
        train.removeAllItems();
        train.addItem("Pakistan Express");
        train.addItem("Rehman Baba Express");
        }
        }
        if(coach.getSelectedItem().equals("DOWN")){
            if((toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Hyderabad") ||
                toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Rohri") ||
                toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Khanewal")) ||
            (toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Lahore")) ||
            (toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Rohri") ||
                toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Khanewal") ||
                toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Khanewal"))){
            train.removeAllItems();
            train.addItem("Pakistan Express");
            train.addItem("Rehman Baba Express");
            train.addItem("Korakaram Express");
            train.addItem("Shalimar Express");
            train.addItem("Bussiness Express");
        }else if((toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Hyderabad") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Rohri") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Khanewal")) ||
        toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Faisalabad") ||
        toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Lahore") ||
        (toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Rohri") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Khanewal") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Faisalabad") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Lahore") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Khanewal") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Faisalabad") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Lahore") ||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Faisalabad") ||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Lahore")) ||
        toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Lahore") ){
        train.removeAllItems();
        train.addItem("Pakistan Express");
        train.addItem("Rehman Baba Express");
        train.addItem("Korakaram Express");
        }else if((toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Hyderabad") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Rohri") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Khanewal")) ||
        toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Sahiwal") ||
        toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Lahore") ||
        (toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Rohri") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Khanewal") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Sahiwal") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Lahore") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Khanewal") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Sahiwal") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Lahore") ||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Sahiwal") ||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Lahore")) ||
        toSt.getSelectedItem().equals("Sahiwal") && frmSt.getSelectedItem().equals("Lahore")){
        train.removeAllItems();
        train.addItem("Shalimar Express");
        train.addItem("Bussiness Express");
        }else if((toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Hyderabad") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Rohri") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Khanewal") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Faisalabad") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Lahore") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Sialkot") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Gujrat") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Jehlum") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Islamabad") ||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Rawalpindi")||
            toSt.getSelectedItem().equals("Karachi") && frmSt.getSelectedItem().equals("Peshawar"))     ||
        (  toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Rohri") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Khanewal") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Faisalabad") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Lahore") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Sialkot") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Gujrat") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Jehlum") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Islamabad") ||
            toSt.getSelectedItem().equals("Hyderabad") && frmSt.getSelectedItem().equals("Rawalpindi")||
            toSt.getSelectedItem().equals("Hyderabad") && toSt.getSelectedItem().equals("Peshawar"))     ||
        ( toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Khanewal") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Faisalabad") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Lahore") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Sialkot") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Gujrat") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Jehlum") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Islamabad") ||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Rawalpindi")||
            toSt.getSelectedItem().equals("Rohri") && frmSt.getSelectedItem().equals("Peshawar"))          ||
        ( toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Faisalabad") ||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Lahore") ||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Sialkot") ||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Gujrat") ||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Jehlum") ||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Islamabad") ||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Rawalpindi")||
            toSt.getSelectedItem().equals("Khanewal") && frmSt.getSelectedItem().equals("Peshawar"))       ||
        ( toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Lahore") ||
            toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Sialkot") ||
            toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Gujrat") ||
            toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Jehlum") ||
            toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Islamabad") ||
            toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Rawalpindi")||
            toSt.getSelectedItem().equals("Faisalabad") && frmSt.getSelectedItem().equals("Peshawar"))  ||
        ( toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Sialkot") ||
            toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Gujrat") ||
            toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Jehlum") ||
            toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Islamabad") ||
            toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Rawalpindi")||
            toSt.getSelectedItem().equals("Lahore") && frmSt.getSelectedItem().equals("Peshawar")) ||
        ( toSt.getSelectedItem().equals("Sialkot") && frmSt.getSelectedItem().equals("Gujrat") ||
            toSt.getSelectedItem().equals("Sialkot") && frmSt.getSelectedItem().equals("Jehlum") ||
            toSt.getSelectedItem().equals("Sialkot") && frmSt.getSelectedItem().equals("Islamabad") ||
            toSt.getSelectedItem().equals("Sialkot") && frmSt.getSelectedItem().equals("Rawalpindi")||
            toSt.getSelectedItem().equals("Sialkot") && frmSt.getSelectedItem().equals("Peshawar")) ||
        ( toSt.getSelectedItem().equals("Gujrat") && frmSt.getSelectedItem().equals("Jehlum") ||
            toSt.getSelectedItem().equals("Gujrat") && frmSt.getSelectedItem().equals("Islamabad") ||
            toSt.getSelectedItem().equals("Gujrat") && frmSt.getSelectedItem().equals("Rawalpindi")||
            toSt.getSelectedItem().equals("Gujrat") && frmSt.getSelectedItem().equals("Peshawar")) ||
        ( toSt.getSelectedItem().equals("Jehlum") && frmSt.getSelectedItem().equals("Islamabad") ||
            toSt.getSelectedItem().equals("Jehlum") && frmSt.getSelectedItem().equals("Rawalpindi")||
            toSt.getSelectedItem().equals("Jehlum") && frmSt.getSelectedItem().equals("Peshawar")) ||
        ( toSt.getSelectedItem().equals("Islamabad") && frmSt.getSelectedItem().equals("Rawalpindi")||
            toSt.getSelectedItem().equals("Islamabad") && frmSt.getSelectedItem().equals("Peshawar")) ||
        ( toSt.getSelectedItem().equals("Rawalpindi") && frmSt.getSelectedItem().equals("Peshawar"))){
        train.removeAllItems();
        train.addItem("Pakistan Express");
        train.addItem("Rehman Baba Express");
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void toStActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toStActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toStActionPerformed

    private void frmStActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmStActionPerformed
       if(coach.getSelectedItem().equals("UP")){
            if(frmSt.getSelectedItem().equals("Karachi")){
                toSt.removeAllItems();
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
                toSt.addItem("Sahiwal");
                toSt.addItem("Faisalabad");
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Hyderabad")){
                toSt.removeAllItems();
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
                toSt.addItem("Sahiwal");
                toSt.addItem("Faisalabad");
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Rohri")){
                toSt.removeAllItems();
                toSt.addItem("Khanewal");
                toSt.addItem("Sahiwal");
                toSt.addItem("Faisalabad");
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Khanewal")){
                toSt.removeAllItems();
                toSt.addItem("Faisalabad");
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Sahiwal")){
                toSt.removeAllItems();
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Faisalabad")){
                toSt.removeAllItems();
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Lahore")){
                toSt.removeAllItems();
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Sialkot")){
                toSt.removeAllItems();
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Gujrat")){
                toSt.removeAllItems();
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Jehlum")){
                toSt.removeAllItems();
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Islamabad")){
                toSt.removeAllItems();
                toSt.addItem("Rawalpindi");
                toSt.addItem("Peshawar");
            }else if(frmSt.getSelectedItem().equals("Rawalpindi")){
                toSt.removeAllItems();
                toSt.addItem("Peshawar");
            }
        }if(coach.getSelectedItem().equals("DOWN")){
            if(frmSt.getSelectedItem().equals("Peshawar")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
                toSt.addItem("Sahiwal");
                toSt.addItem("Faisalabad");
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
                toSt.addItem("Rawalpindi");
            }else if(frmSt.getSelectedItem().equals("Rawalpindi")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
                toSt.addItem("Sahiwal");
                toSt.addItem("Faisalabad");
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
                toSt.addItem("Islamabad");
            }else if(frmSt.getSelectedItem().equals("Islamabad")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
                toSt.addItem("Sahiwal");
                toSt.addItem("Faisalabad");
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
                toSt.addItem("Jehlum");
            }else if(frmSt.getSelectedItem().equals("Jehlum")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
                toSt.addItem("Sahiwal");
                toSt.addItem("Faisalabad");
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
                toSt.addItem("Gujrat");
            }else if(frmSt.getSelectedItem().equals("Gujrat")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
                toSt.addItem("Sahiwal");
                toSt.addItem("Faisalabad");
                toSt.addItem("Lahore");
                toSt.addItem("Sialkot");
            }else if(frmSt.getSelectedItem().equals("Sialkot")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
                toSt.addItem("Sahiwal");
                toSt.addItem("Faisalabad");
                toSt.addItem("Lahore");
            }else if(frmSt.getSelectedItem().equals("Lahore")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
                toSt.addItem("Sahiwal");
                toSt.addItem("Faisalabad");
            }else if(frmSt.getSelectedItem().equals("Faisalabad")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
            }else if(frmSt.getSelectedItem().equals("Khanewal")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
            }else if(frmSt.getSelectedItem().equals("Sahiwal")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
                toSt.addItem("Rohri");
                toSt.addItem("Khanewal");
            }else if(frmSt.getSelectedItem().equals("Rohri")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
                toSt.addItem("Hyderabad");
            }else if(frmSt.getSelectedItem().equals("Hyderabad")){
                toSt.removeAllItems();
                toSt.addItem("Karachi");
            }
        }
    }//GEN-LAST:event_frmStActionPerformed
    
    private void coachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachActionPerformed
            if(coach.getSelectedItem().equals("UP")){
            frmSt.removeAllItems();
            frmSt.addItem("Karachi");
            frmSt.addItem("Hyderabad");
            frmSt.addItem("Rohri");
            frmSt.addItem("Khanewal");
            frmSt.addItem("Sahiwal");
            frmSt.addItem("Faisalabad");
            frmSt.addItem("Lahore");
            frmSt.addItem("Sialkot");
            frmSt.addItem("Gujrat");
            frmSt.addItem("Jehlum");
            frmSt.addItem("Islamabad");
            frmSt.addItem("Rawalpindi");
            
//            frmSt1.removeAllItems();
//            frmSt1.addItem("Karachi");
//            frmSt1.addItem("Hyderabad");
//            frmSt1.addItem("Rohri");
//            frmSt1.addItem("Khanewal");
//            frmSt1.addItem("Sahiwal");
//            frmSt1.addItem("Faisalabad");
//            frmSt1.addItem("Lahore");
//            frmSt1.addItem("Sialkot");
//            frmSt1.addItem("Gujrat");
//            frmSt1.addItem("Jehlum");
//            frmSt1.addItem("Islamabad");
//            frmSt1.addItem("Rawalpindi");
            }else if(coach.getSelectedItem().equals("DOWN")){
            frmSt.removeAllItems();
            frmSt.addItem("Hyderabad");
            frmSt.addItem("Rohri");
            frmSt.addItem("Khanewal");
            frmSt.addItem("Sahiwal");
            frmSt.addItem("Faisalabad");
            frmSt.addItem("Lahore");
            frmSt.addItem("Sialkot");
            frmSt.addItem("Gujrat");
            frmSt.addItem("Jehlum");
            frmSt.addItem("Islamabad");
            frmSt.addItem("Rawalpindi");
            frmSt.addItem("Peshawar");
            
//            frmSt1.removeAllItems();
//            frmSt1.addItem("Hyderabad");
//            frmSt1.addItem("Rohri");
//            frmSt1.addItem("Khanewal");
//            frmSt1.addItem("Sahiwal");
//            frmSt1.addItem("Faisalabad");
//            frmSt1.addItem("Lahore");
//            frmSt1.addItem("Sialkot");
//            frmSt1.addItem("Gujrat");
//            frmSt1.addItem("Jehlum");
//            frmSt1.addItem("Islamabad");
//            frmSt1.addItem("Rawalpindi");
//            frmSt1.addItem("Peshawar");
            }
    }//GEN-LAST:event_coachActionPerformed

   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    RailwayPro rp = new RailwayPro();
    jLabel2.setText(train.getSelectedItem().toString());
    ResultSet rs;
    rs=rp.getDataFromTable((String)train.getSelectedItem());
    jLabel2.setText((String)train.getSelectedItem());
    DefaultTableModel tbModel = (DefaultTableModel)table.getModel();
    try{
            while(rs.next()){
                String dep = rs.getString("train_dep");
                String arr = rs.getString("train_arr");
                String fromSt = rs.getString("from_st");
                String toSta = rs.getString("to_st");
                String ec = rs.getString("fare_ec");
                String ac = rs.getString("fare_ac");
                String bs = rs.getString("fare_bs");
                String[] tableSet = {dep,arr,fromSt,toSta,ec,ac,bs};
                tbModel.addRow(tableSet);
            }
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void coachItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_coachItemStateChanged
                   
    }//GEN-LAST:event_coachItemStateChanged

    private void coachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coachMouseClicked
        
    }//GEN-LAST:event_coachMouseClicked

    private void coachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coachMousePressed
       
    }//GEN-LAST:event_coachMousePressed

    private void coachPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_coachPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_coachPropertyChange

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Admin a = new Admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userinterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> coach;
    private javax.swing.JComboBox<String> frmSt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDayChooserBeanInfo jDayChooserBeanInfo1;
    private com.toedter.calendar.JDayChooserBeanInfo jDayChooserBeanInfo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> toSt;
    private javax.swing.JComboBox<String> train;
    // End of variables declaration//GEN-END:variables

}